export const projects = [
    {
        id: 'tienda',
        num: '01',
        type: 'FULL STACK',
        name: 'Tienda Musical',
        desc: 'Sistema de gestión de inventario y ventas para una tienda de instrumentos. Autenticación con bcrypt, roles de empleado, CRUD completo, reportes con SQL avanzado (CTEs, RANK, vistas), exportación a CSV y carrito de ventas con useReducer.',
        tech: ['React', 'FastAPI', 'PostgreSQL', 'Docker Compose', 'Material UI', 'Vitest', 'bcrypt'],
        highlights: [
            'Auth real con bcrypt + sesión en AuthContext',
            '8 endpoints de reportes con SQL avanzado',
            'Docker Compose: 3 servicios orquestados',
            'Pruebas unitarias con Vitest + Testing Library',
        ],
        demo: 'https://proyecto2-web.vercel.app/',
        repo: 'https://github.com/LuispeFigueroa/Proyecto2-Web',
        accentColor: '#ff6b2b',
        bgClass: 'vis-tienda',
        label: 'TIENDA',
        full: false,
    },
    {
        id: 'lineup',
        num: '02',
        type: 'FULL STACK',
        name: 'El Lineup',
        desc: 'Plataforma para gestionar ligas de softball/béisbol. Frontend en Vanilla JS, API REST en Go con Gin, PostgreSQL en Railway. Standings en tiempo real, búsqueda, subida de imágenes y exportación a CSV sin librerías.',
        tech: ['Go — Gin', 'PostgreSQL', 'Docker', 'Vanilla JS', 'Railway', 'GitHub Pages'],
        highlights: [
            'API en Go deployada en Railway en producción',
            'Generación de CSV sin librerías desde el browser',
            '21 endpoints REST con validación server-side',
            'Frontend y backend en repos separados',
        ],
        demo: 'https://luispefigueroa.github.io/ellineup-client',
        repo: 'https://github.com/LuispeFigueroa/ellineup-client',
        repoBack: 'https://github.com/LuispeFigueroa/ellineup-api',
        accentColor: '#c084fc',
        bgClass: 'vis-lineup',
        label: 'LINEUP',
        full: false,
    },
    {
        id: 'onta',
        num: '03',
        type: 'FRONTEND SPA',
        name: '¿ONTA?',
        desc: 'Mini-blog de películas con la API de TMDB. Muestra información, tendencias semanales y en qué plataforma de streaming está cada película. SPA con React Router v6, Context API, tema claro/oscuro y favoritos persistentes.',
        tech: ['React', 'Vite', 'React Router v6', 'Context API', 'TMDB API'],
        highlights: [
            '4 rutas con React Router v6',
            'Estado global: tema + favoritos en Context',
            'Componentes documentados con tabla de props',
            '5 endpoints de TMDB integrados',
        ],
        demo: null,
        repo: 'https://github.com/LuispeFigueroa/Ejercicio04WEB',
        accentColor: '#ffb347',
        bgClass: 'vis-onta',
        label: 'ONTA?',
        full: false,
    },
    {
        id: 'calc',
        num: '04',
        type: 'REACT + TESTING',
        name: 'Calculadora',
        desc: 'Calculadora con React + TypeScript. Pruebas unitarias con Vitest, documentación de componentes en Storybook y pruebas de browser con Playwright. Demuestra flujo de trabajo con calidad de código.',
        tech: ['React', 'TypeScript', 'Vitest', 'Storybook', 'Playwright'],
        highlights: [],
        demo: 'https://luispefigueroa.github.io/Lab07-Web/',
        repo: 'https://github.com/LuispeFigueroa/Lab07-Web',
        accentColor: '#ff6b2b',
        bgClass: 'vis-calc',
        label: 'CALC',
        full: true,
    },
    {
        id: 'snake',
        num: '05',
        type: 'REACT GAME',
        name: 'Snake',
        desc: 'Juego Snake clásico en React. Manejo de estado con useState/useEffect, game loop, niveles de dificultad progresivos y componentes separados por responsabilidad.',
        tech: ['React', 'Vite', 'useState', 'useEffect'],
        highlights: [],
        demo: null,
        repo: 'https://github.com/LuispeFigueroa/Lab-6-Snake-',
        accentColor: '#c084fc',
        bgClass: 'vis-snake',
        label: 'SNAKE',
        full: true,
    },
]